blog/urls.py
from django.contrib import admin
from . import settings
from django.urls import path, include
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls')),
    path('', include('authentication.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('post/<str:slug>', views.details, name="blog-details"),
    path('create-post/', views.createPost, name="create-post"),
    path('update/<str:slug>', views.editPost, name="update"),
    path('delete/<str:slug>', views.deletePost, name="delete"),
]

post/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=50, null=True, blank=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = "Categories"


    def save(self,*args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name
    

class Blog_Post(models.Model):
    title = models.CharField(max_length=254, unique=True)
    slug = models.SlugField(max_length=254, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    content = models.TextField()
    image = models.ImageField(upload_to="posts/")
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    is_featured = models.BooleanField(default=False)


    def save(self,*args, **kwargs):
        self.slug = slugify(self.title)
        super(Blog_Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Blog Post"
        verbose_name_plural = "Blog Posts"

post/forms.py
from django import forms
from django.forms.widgets import TextInput
from post.models import Blog_Post, Category

class createPostForm(forms.ModelForm):
    title = forms.CharField(
        max_length=200,
        required=True,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'
            }
        )
    )
    category = forms.ModelChoiceField(
        queryset=Category.objects.all().filter(is_active=True),
        widget=forms.Select(
            attrs={
                'class': 'form-control',
            }
        )
    )

    content = forms.CharField(
        required=True,
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'rows':'3'
            }
        )
    )

    image = forms.ImageField(
        required=True,
        widget=forms.FileInput(
            attrs={
                'class': 'form-control',
            }
        )
    )


    
    is_active = forms.BooleanField(required=False,initial=True)
    is_featured = forms.BooleanField(required=False,initial=False)
    
    class Meta:
        model = Blog_Post
        fields = ['title','category', 'content', 'image','is_featured', 'is_active']

post/views.py
from django.contrib import messages
from django.contrib.auth import login
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from .models import Category, Blog_Post
from django.db.models.aggregates import Count
from django.db.models import Q
from next_prev import next_in_order, prev_in_order
from .forms import createPostForm
from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):
    search_category = request.GET.get('category',"")
    q = request.GET.get('q',"")

    if not search_category == "":
        posts = Blog_Post.objects.all().filter(
        category__name__icontains=search_category
        ).order_by("-created_at").exclude(is_featured=True)
        post_count = posts.count()
    elif not q == "":
        posts = Blog_Post.objects.all().filter(
        Q(title__icontains=q) | 
        Q(author__username__icontains=q)
        ).order_by("-created_at")
        post_count = posts.count()
    else:
        posts = Blog_Post.objects.all().order_by("-created_at").exclude(is_featured=True)
        post_count = posts.count()
    
    categories = Category.objects.all().filter(is_active=True)
    paginator = Paginator(posts, 2)
    page_number = request.GET.get('page', 1)
    
    try:
        page_content = paginator.page(page_number)
    except PageNotAnInteger:
        page_content = paginator.page(1)
    except EmptyPage:
        page_content = paginator.page(paginator.num_pages)

    feature_post = Blog_Post.objects.all().filter(is_featured=True).order_by("-created_at")[:1]

    context = {
        'search_category':search_category,
        'categories':categories,
        'page_content':page_content,
        'feature_post':feature_post,
        'q':q,
        'post_count':post_count
    }
    return render(request, 'post/index.html', context)

def details(request, slug):
    categories = Category.objects.annotate(num_posts=Count('blog_post')).filter(is_active=True)
    post = Blog_Post.objects.get(slug=slug)
    previous_post = prev_in_order(post)
    next_post = next_in_order(post)

    context = {
        'post':post,
        'categories':categories,
        'previous_post':previous_post,
        'next_post':next_post,
    }
    return render(request, 'post/post-details.html', context)


@login_required(login_url="/login")
def createPost(request):
    categories = Category.objects.all().filter(is_active=True)
    form = createPostForm()
    if request.method == "POST":
        title = request.POST.get('title')
        if title == "":
            messages.error(request, "Title field is required.")
            return HttpResponseRedirect('/create-post')
        category = Category.objects.get(id=request.POST.get('category'))   
        content = request.POST.get('content')
        if content == "":
            messages.error(request, "Content field is required.")
            return HttpResponseRedirect('/create-post')
        image = request.FILES.get('image')
        if image == "":
            messages.error(request, "Image field is required.")
            return HttpResponseRedirect('/create-post')

        is_active = request.POST.get('is_active')
        is_featured = request.POST.get('is_featured')

        if is_active == "on":
            is_active = True
        else:
            is_active = False

        if is_featured == "on":
            is_featured = True
        else:
            is_featured = False

        post = Blog_Post.objects.create(
            title = title,
            category = category,
            author = request.user,
            content = content,
            image = image,
            is_active = is_active,
            is_featured = is_featured,
        )
        post.save()
        messages.success(request, f"{title} is Created Successfully.")
        return HttpResponseRedirect('/create-post')

    context = {
        'form':form,
        'categories':categories,
    }
    return render(request, 'post/create-post.html', context)


@login_required(login_url="/login")
def editPost(request, slug):
    post = Blog_Post.objects.get(slug=slug)
    if request.method == "POST":
        form = createPostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
        messages.success(request, "Post Updated Successfully.")
        return HttpResponseRedirect('/profile')
    else:
        form = createPostForm(instance=post)

    context = {
        'form':form,
        'editable_post':post,
    }
    return render(request, 'post/edit-post.html', context)

@login_required(login_url='/login')
def deletePost(request, slug):
    post = Blog_Post.objects.get(slug=slug)
    post.delete()
    messages.success(request, "Post Deleted Successfully.")
    return HttpResponseRedirect('/profile')

post/templates/post/create-post.html
{% extends 'post/header.html' %}
{% block title %}Create Post{% endblock title%}
{% block body %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-12 order-md-1">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/">Home</a></li>
                    <li class="breadcrumb-item"><a href="#">{{'Post'}}</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Create Post</li>
                </ol>
            </nav>
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{message.tags}}{% endif %}
                alert-dismissible" role="alert">
                <div id="form_errors">
                    <strong>{{message}}</strong>
                </div>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endfor %}
            {% endif %}
            <form class="needs-validation" enctype="multipart/form-data" action="{% url 'create-post' %}" method="POST">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-12 mb-3">
                        <label for="firstName">Title</label>
                        {{form.title}}
                    </div>
                </div>
                <div class="mb-3">
                    <label for="lastName">Category</label>
                    <select name="category" id="category" class="form-control">
                        {% for category in categories %}
                        <option value="{{category.id}}">{{category.name}}</option>
                        {% endfor %}
                    </select>

                </div>
                <div class="mb-3">
                    <label for="email">Content </label>
                    {{form.content}}
                </div>
                <div class="mb-3">
                    <label for="email">Feature Image </label>
                    {{form.image}}
                </div>
                <div class="mb-3">
                    <label for="id_is_active">Is Active ? </label>
                    {{form.is_active}}
                </div>
                <div class="mb-3">
                    <label for="id_is_featured">Is Featured Post ? </label>
                    {{form.is_featured}}
                </div>
                <div class="row d-flex justify-content-end">
                    <div class="col-md-4 ml-0 ">
                        <button class="btn btn-success btn-lg btn-block" type="submit">Create Post</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock body%}

post/templates/post/edit-post.html
{% extends 'post/header.html' %}
{% block title %} Update {{editable_post.title}}{% endblock title%}
{% block body %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-12 order-md-1">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/">Home</a></li>
                    <li class="breadcrumb-item"><a href="#">Post</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{editable_post.title}}</li>
                </ol>
            </nav>
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{message.tags}}{% endif %}
                alert-dismissible" role="alert">
                <div id="form_errors">
                    <strong>{{message}}</strong>
                </div>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endfor %}
            {% endif %}
            <form action="{% url 'update' editable_post.slug %}" class="needs-validation" enctype="multipart/form-data"
                method="POST">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-12 mb-3">
                        <label for="firstName">Title</label>
                        {{form.title}}
                    </div>
                </div>
                <div class="mb-3">
                    <label for="lastName">Category</label>
                    {{form.category}}
                </div>
                <div class="mb-3">
                    <label for="email">Content </label>
                    <textarea class="form-control" name="content" id="content" cols="30"
                        rows="3">{{editable_post.content}}</textarea>
                </div>
                <div class="mb-3">
                    <label for="image">Feature Image </label>
                    <p>Current Image <a href="{{editable_post.image.url}}"
                            target="_blank">{{editable_post.image.url}}</a></p>
                    {{form.image}}
                </div>
                <div class="mb-3">
                    <label for="is_active">Is Active ? </label>
                    {{form.is_active}}
                </div>
                <div class="mb-3">
                    <label for="is_featured">Is Featured post ? </label>
                    {{form.is_featured}}
                </div>
                <div class="row d-flex justify-content-end">
                    <div class="col-md-2 ml-0 ">
                        <a class="btn btn-danger btn-lg btn-block" href="{% url 'delete' editable_post.slug %}">Delete
                            Post</a>
                    </div>
                    <div class="col-md-2 ml-0 ">
                        <button class="btn btn-info btn-lg btn-block" type="submit">Update Post</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock body%}

post/templates/post/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{% block title%}{% endblock title%} | Django Blog</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" />
        <style>
            body {
                overflow-x: hidden;
            }

            .blog-footer {
                margin-top: 20px;
                padding: 1rem 0;
                color: #999;
                text-align: center;
                background-color: #f9f9f9;
                border-top: .05rem solid #e5e5e5;
            }

            .blog-footer p:last-child {
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <div class="container mt-3">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark rounded justify-content-between">
                <a class="navbar-brand" href="/">MyBlog</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item ">
                            <a class="nav-link" href="#">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Contact us </a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Welcome Back {{user.username|capfirst}}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'userprofile' %}">Profile</a>
                                <a class="dropdown-item" href="{% url 'create-post' %}">Create Blog</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                            </div>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">Login </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'register' %}">Register </a>
                        </li>
                        {% endif %}
                    </ul>
                    <form class="form-inline my-2 my-lg-0" action="/" method="GET">
                        <input required class="form-control mr-sm-2" name="q" type="search" placeholder="Search..."
                            aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </nav>
        </div>
        {% block body%} {% endblock body %}
        <div class="container mt-3">
            <footer class="blog-footer rounded">
                <p>Blog template built for <a href="#">Bootstrap</a>.</p>
                <p>
                    <a href="#">Back to top</a>
                </p>
            </footer>
        </div>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    </body>
</html>

post/templates/post/index.html
{% extends 'post/header.html'%}
{% load static %}
{% load humanize %}

{% block title %} Home {% endblock title %}
{% block body %}
<div class="container">
    <div class="nav-scroller py-1 mb-2">
        <nav class="nav d-flex justify-content-start">
            {% for category in categories %}
            <a class="p-2 text-info font-weight-bold" href="?category={{category.slug}}">{{ category.name }}</a>
            {% endfor %}
        </nav>
    </div>
    {% if search_category == "" %}
    {% for feature in feature_post %}
    <div class="jumbotron p-3 p-md-5  rounded " style="background-image: linear-gradient(0deg, rgba(0,0,0,0.5), rgba(0, 0, 0, 0.5)),url('{{feature.image.url}}'); background-repeat: no-repeat;
    background-position: center; ">
        <div class="col-md-12 px-0">
            <h1 class="display-4 text-white font-weight-bold">{{feature.title}}</h1>
            <p class="lead my-3 text-white">{{feature.content|truncatechars:"300"}}</p>
            <p class="lead mb-0"><a href="{% url 'blog-details' feature.slug %}"
                    class="text-warning font-weight-bold">Continue reading...</a>
            </p>
        </div>
    </div>
    {% endfor %}
    {% endif %}

    <div class="row mb-2">
        {% if search_category == "" %}
        {% for post in page_content %}
        <div class="col-md-6">
            <div class="card flex-md-row mb-4 box-shadow h-md-250">
                <div class="row">
                    <div class="col-lg-8 col-md-12 col-sm-12">
                        <div class="card-body d-flex flex-column align-items-start">
                            <strong class="d-inline-block mb-2 text-success">{{post.category}}</strong>
                            <h3 class="mb-0">
                                <a class="text-dark" href="{% url 'blog-details' post.slug %}">
                                    {{post.title}}
                                </a>
                            </h3>
                            <div class="mb-1 text-muted">{{post.created_at|naturaltime}}</div>
                            <p class="card-text mb-auto">{{post.content|truncatechars:"100"}}</p>
                            <a href="{% url 'blog-details' post.slug %}" class="mt-2 text-warning">Continue
                                reading...</a>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-12 col-sm-12">
                        <img class="img-fluid rounded h-100 w-100" src="{{post.image.url}}" alt="{{post.title}}">
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <div class="col-md-12">
            <div class="alert alert-info" role="alert">
                We found {{ page_content|length }} post{{ page_content|pluralize }} of category
                "{{search_category|capfirst}}".
            </div>
        </div>
        {% for post in page_content %}
        <div class="col-md-6">
            <div class="card flex-md-row mb-4 box-shadow h-md-250">
                <div class="row">
                    <div class="col-lg-8 col-md-12 col-sm-12">
                        <div class="card-body d-flex flex-column align-items-start">
                            <strong class="d-inline-block mb-2 text-primary">{{post.category}}</strong>
                            <h3 class="mb-0">
                                <a class="text-dark" href="{% url 'blog-details' post.slug %}">{{post.title}}</a>
                            </h3>
                            <div class="mb-1 text-muted">{{post.created_at|naturaltime}}</div>
                            <p class="card-text mb-auto">{{post.content|truncatechars:"100"}}</p>
                            <a href="{% url 'blog-details' post.slug %}">Continue reading...</a>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-12 col-sm-12">
                        <img class="img-fluid rounded h-100 w-100" src="{{post.image.url}}" alt="{{post.title}}">
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        {% endif %}

        {% if not q == "" %}
        {% if post_count == 0 %}
        <div class="col-md-12">
            <div class="alert alert-danger" role="alert">
                We could not found anything related to
                "<b>{{q}}</b>".
            </div>
        </div>
        {% endif %}
        {% endif %}
    </div>
    {% if page_content.has_other_pages %}
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if page_content.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{page_content.previous_page_number}}">Previous</a>
            </li>
            {% else %}
            <li class="page-item disabled"><a class="page-link disabled" href="#">Previous</a></li>
            {% endif %}
            <li class="page-item"><a class="page-link" href="#">{{page_content.number}} of
                    {{page_content.paginator.num_pages}}</a></li>
            {% if page_content.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{page_content.next_page_number}}">Next</a>
            </li>
            {% else %}
            <li class="page-item disabled"><a class="page-link disabled" href="#">Next</a></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
{% endblock body %}

post/templates/post/post-details.html
{% extends 'post/header.html' %}
{% block title %}{{post.title}} {% endblock title%}
{% block body %}
<main role="main" class="container mt-3">
    <div class="row">
        <div class="col-md-8 blog-main">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/">Home</a></li>
                    <li class="breadcrumb-item"><a href="#">Posts</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{post.title}}</li>
                </ol>
            </nav>
            <img class="img-fluid rounded" src="{{post.image.url}}" alt="{{post.title}}">
            <div class="blog-post">
                <h2 class="blog-post-title">{{post.title}}</h2>
                <p class="blog-post-meta">{{post.created_at}} by <a href="#">{{post.author.first_name}}
                        {{post.author.last_name}}</a></p>
                <p>{{post.content}}</p>
            </div>
            <nav class="blog-pagination">
                {% if previous_post %}
                <a class="btn btn-outline-info" href="{% url 'blog-details' previous_post.slug%}">Previous</a>
                {% endif %}
                {% if next_post %}
                <a class="btn btn-outline-warning" href="{% url 'blog-details' next_post.slug %}">Next</a>
                {% endif %}
            </nav>
        </div>
        <aside class="col-md-4 blog-sidebar">
            <div class="p-3">
                <h4 class="font-weight-bold">Categories</h4>
                <hr>
                <ol class="list-unstyled mb-0">
                    {% for category in categories %}
                    <li><a href="/?category={{category.name}}">{{ category.name }} ({{category.num_posts}})</a></li>
                    {% endfor %}
                </ol>
            </div>
            <div class="p-3">
                <h4 class="font-weight-bold">Elsewhere</h4>
                <hr>
                <ol class="list-unstyled">
                    <li><a href="#">GitHub</a></li>
                    <li><a href="#">Twitter</a></li>
                    <li><a href="#">Facebook</a></li>
                </ol>
            </div>
        </aside>
    </div>
</main>
{% endblock body %}